# CI configuration file
name: CI

on:
  push:
    branches:
      - 'dev/**'

  pull_request:

  workflow_dispatch:

env:
  BUILD_JOBS: 4
  TEST_JOBS: 8
  CCACHE_DIR: "/tmp/ccache_dir"
  CHECK: check-world PROVE_FLAGS=--timer
  CHECKFLAGS: -Otarget
  MBUILD_TARGET: all testprep
  MTEST_ARGS: --print-errorlogs --no-rebuild -C build
  RUN_TESTS: false
  CI_LINUX: false
  CI_COMPILERWARNINGS: false
  CI_WINDOWS: true

  LINUX_CONFIGURE_FEATURES: |
    --with-gssapi \
    --with-icu \
    --with-ldap \
    --with-libcurl \
    --with-libxml \
    --with-libxslt \
    --with-llvm \
    --with-lz4 \
    --with-pam \
    --with-perl \
    --with-python \
    --with-selinux \
    --with-ssl=openssl \
    --with-systemd \
    --with-tcl \
    --with-uuid=ossp \
    --with-zstd \

  LINUX_MESON_FEATURES: "-Duuid=e2fs"

  # Postgres config args for the meson builds, shared between all meson tasks
  # except the sanity-check task.
  MESON_COMMON_PG_CONFIG_ARGS: "-Dcassert=true -Dinjection_points=true"

jobs:
  # Since we cannot share variables between jobs, create a job that other jobs
  # depend on it to provide parameters. These parameters are used to control
  # the workflow execution.
  prepare:
    name: Set parameters
    runs-on: ubuntu-24.04
    outputs:
      ci_linux: ${{ steps.id-ci-linux.outputs.ci_linux }}
      ci_compilerwarnings: ${{ steps.id-ci-compiler-warnings.outputs.ci_compilerwarnings }}
      ci_windows: ${{ steps.id-ci-windows.outputs.ci_windows }}
    steps:
      - name: Enable CI Linux
        id: id-ci-linux
        run: echo "ci_linux=$CI_LINUX" >> $GITHUB_OUTPUT
      - name: Enable CI Compiler Warnings
        id: id-ci-compiler-warnings
        run: echo "ci_compilerwarnings=$CI_COMPILERWARNINGS" >> $GITHUB_OUTPUT
      - name: Enable CI Windows
        id: id-ci-windows
        run: echo "ci_windows=$CI_WINDOWS" >> $GITHUB_OUTPUT

  # Don't waste cycles if there is a broken commit. This job aims to build and
  # run a minimal test. All other jobs depend on it.
  sanity-check:
    name: Sanity Check
    runs-on: ubuntu-24.04
    env:
      CCACHE_MAXSIZE: "150M"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          repository: postgres/postgres
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_SLONIK }}

      - name: System information
        run: |
          id
          uname -a
          cat /proc/cmdline
          ulimit -a -H && ulimit -a -S
          export

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf bison clang flex gdb gettext \
          libcurl4-openssl-dev libicu-dev libio-pty-perl libipc-run-perl \
          libkrb5-dev libldap2-dev liblz4-dev libnuma-dev libpam0g-dev \
          libperl-dev libreadline-dev libselinux1-dev libssl-dev \
          libsystemd-dev liburing-dev libxml2-dev libxml2-utils libxslt1-dev \
          libzstd-dev llvm-dev lz4 mawk perl pkgconf python3-dev \
          systemtap-sdt-dev tcl-dev tzdata uuid-dev xsltproc zlib1g-dev zstd \
          libossp-uuid-dev ccache meson

      - name: Configure
        run: |
          meson setup --buildtype=debug --auto-features=disabled \
            -Dtap_tests=enabled build

      - name: Build
        run: |
          ninja -C build -j${{ env.BUILD_JOBS }} ${{ env.MBUILD_TARGET }}

      # Cache is immutable. You cannot updated it after creating. Hence, you
      # can only save once for this workflow. There isn't another attempt to
      # save the cache in another job because any job failure stops this
      # workflow.
      - name: Upload cache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: cache-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Minimal Test
        run: |
          ulimit -c unlimited
          meson test ${{ env.MTEST_ARGS }} --suite setup
          meson test ${{ env.MTEST_ARGS }} \
            --num-processes ${{ env.TEST_JOBS }} \
            cube/regress pg_ctl/001_start_stop

  compiler-warnings:
    name: Compiler warnings
    needs: [prepare, sanity-check]
    if: ${{ needs.prepare.outputs.ci_compilerwarnings }}
    runs-on: ubuntu-24.04
    env:
      CCACHE_MAXSIZE: "250M"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          repository: postgres/postgres
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_SLONIK }}

      # Restore the cache saved in the sanity-check job
      - name: Populate cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: cache-${{ runner.os }}-${{ runner.arch }}--${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: cache-${{ runner.os }}-${{ runner.arch }}-

      - name: System information
        run: |
          id
          uname -a
          cat /proc/cmdline
          ulimit -a -H && ulimit -a -S
          gcc -v
          clang -v
          export

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf bison clang flex gdb gettext \
          libcurl4-openssl-dev libicu-dev libio-pty-perl libipc-run-perl \
          libkrb5-dev libldap2-dev liblz4-dev libnuma-dev libpam0g-dev \
          libperl-dev libreadline-dev libselinux1-dev libssl-dev \
          libsystemd-dev liburing-dev libxml2-dev libxml2-utils libxslt1-dev \
          libzstd-dev llvm-dev lz4 mawk perl pkgconf python3-dev \
          systemtap-sdt-dev tcl-dev tzdata uuid-dev xsltproc zlib1g-dev zstd \
          libossp-uuid-dev ccache

      - name: Setup script
        run: |
          echo "COPT=-Werror" > src/Makefile.custom

      # gcc, cassert off, dtrace on
      - name: gcc - dtrace
        if: ${{ !cancelled() }}
        run: |
          time ./configure \
            --cache gcc.cache \
            --enable-dtrace \
            ${{ env.LINUX_CONFIGURE_FEATURES }}
            CC="ccache gcc" CXX="ccache g++" CLANG="ccache clang"
          make -s -j${{ env.BUILD_JOBS }} clean
          time make -s -j${{ env.BUILD_JOBS }} world-bin

      # gcc, cassert on, dtrace off
      - name: gcc - cassert
        if: ${{ !cancelled() }}
        run: |
          time ./configure \
            --cache gcc.cache \
            --enable-cassert \
            ${{ env.LINUX_CONFIGURE_FEATURES }}
            CC="ccache gcc" CXX="ccache g++" CLANG="ccache clang"
          make -s -j${{ env.BUILD_JOBS }} clean
          time make -s -j${{ env.BUILD_JOBS }} world-bin

      # clang, cassert off, dtrace off
      - name: clang
        if: ${{ !cancelled() }}
        run: |
          time ./configure \
            --cache clang.cache \
            ${{ env.LINUX_CONFIGURE_FEATURES }}
            CC="ccache clang" CXX="ccache clang++" CLANG="ccache clang"
          make -s -j${{ env.BUILD_JOBS }} clean
          time make -s -j${{ env.BUILD_JOBS }} world-bin

      # clang, cassert on, dtrace on
      - name: clang - cassert - dtrace
        if: ${{ !cancelled() }}
        run: |
          time ./configure \
            --cache clang.cache \
            --enable-cassert \
            --enable-dtrace \
            ${{ env.LINUX_CONFIGURE_FEATURES }}
            CC="ccache clang" CXX="ccache clang++" CLANG="ccache clang"
          make -s -j${{ env.BUILD_JOBS }} clean
          time make -s -j${{ env.BUILD_JOBS }} world-bin

      # headerscheck
      - name: headerscheck
        if: ${{ !cancelled() }}
        run: |
          time ./configure \
            --quiet \
            ${{ env.LINUX_CONFIGURE_FEATURES }}
            CC="gcc" CXX="g++" CLANG="clang"
          make -s -j${{ env.BUILD_JOBS }} clean
          time make -s headerscheck EXTRAFLAGS='-fmax-errors=10'

      # cpluspluscheck
      - name: cpluspluscheck
        if: ${{ !cancelled() }}
        run: |
          time make -s cpluspluscheck EXTRAFLAGS='-fmax-errors=10'

  linux-autoconf:
    name: Linux - Ubuntu noble - Autoconf
    needs: [prepare, sanity-check]
    if: ${{ needs.prepare.outputs.ci_linux }}
    runs-on: ubuntu-24.04
    env:
      CCACHE_MAXSIZE: "250M"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          repository: postgres/postgres
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_SLONIK }}

      # Restore the cache saved in the sanity-check job
      - name: Populate cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: cache-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: cache-${{ runner.os }}-${{ runner.arch }}-

      - name: System information
        run: |
          id
          uname -a
          cat /proc/cmdline
          ulimit -a -H && ulimit -a -S
          export

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf bison clang flex gdb gettext \
          libcurl4-openssl-dev libicu-dev libio-pty-perl libipc-run-perl \
          libkrb5-dev libldap2-dev liblz4-dev libnuma-dev libpam0g-dev \
          libperl-dev libreadline-dev libselinux1-dev libssl-dev \
          libsystemd-dev liburing-dev libxml2-dev libxml2-utils libxslt1-dev \
          libzstd-dev llvm-dev lz4 mawk perl pkgconf python3-dev \
          systemtap-sdt-dev tcl-dev tzdata uuid-dev xsltproc zlib1g-dev zstd \
          libossp-uuid-dev ccache

      - name: Configure
        run: |
          ./configure \
            --enable-cassert --enable-injection-points --enable-debug \
            --enable-tap-tests --enable-nls \
            --with-segsize-blocks=6 \
            --with-libnuma \
            --with-liburing \
            ${{ env.LINUX_CONFIGURE_FEATURES }}
            CLANG="ccache clang"

      - name: Build
        run: |
          make -s -j${{ env.BUILD_JOBS }} world-bin

      - name: Run tests
        if: env.RUN_TESTS
        run: |
          ulimit -c unlimited # default is 0
          make -s ${{ env.CHECK }} ${{ env.CHECKFLAGS }} -j${{ env.TEST_JOBS }}

  linux-meson:
    name: Linux - Ubuntu noble - Meson
    needs: [prepare, sanity-check]
    if: ${{ needs.prepare.outputs.ci_linux }}
    runs-on: ubuntu-24.04
    env:
      CCACHE_MAXSIZE: "400M"
      SANITIZER_FLAGS: "-fsanitize=alignment,undefined"
      PG_TEST_INITDB_EXTRA_OPTS: "-c io_method=io_uring"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          repository: postgres/postgres
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_SLONIK }}

      # Restore the cache saved in the sanity-check job
      - name: Populate cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: cache-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: cache-${{ runner.os }}-${{ runner.arch }}-

      - name: System information
        run: |
          id
          uname -a
          cat /proc/cmdline
          ulimit -a -H && ulimit -a -S
          export

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf bison clang flex gdb gettext \
          libcurl4-openssl-dev libicu-dev libio-pty-perl libipc-run-perl \
          libkrb5-dev libldap2-dev liblz4-dev libnuma-dev libpam0g-dev \
          libperl-dev libreadline-dev libselinux1-dev libssl-dev \
          libsystemd-dev liburing-dev libxml2-dev libxml2-utils libxslt1-dev \
          libzstd-dev llvm-dev lz4 mawk perl pkgconf python3-dev \
          systemtap-sdt-dev tcl-dev tzdata uuid-dev xsltproc zlib1g-dev zstd \
          libossp-uuid-dev ccache meson

      - name: Configure
        run: |
          meson setup \
            ${{ env.MESON_COMMON_PG_CONFIG_ARGS }} \
            --buildtype=debug \
            ${{ env.LINUX_MESON_FEATURES }} \
            -Dllvm=enabled \
            build

      - name: Build
        run: |
          ninja -C build -j${{ env.BUILD_JOBS }} ${{ env.MBUILD_TARGET }}
          ninja -C build -t missingdeps

      - name: Test
        run: |
          ulimit -c unlimited
          meson test ${{ env.MTEST_ARGS }} --num-processes ${{ env.TEST_JOBS }}

  windows-meson:
    name: Windows - Server 2022 - Meson
    needs: [prepare, sanity-check]
    if: ${{ needs.prepare.outputs.ci_windows }}
    runs-on: windows-2022
    env:
      VCVARS_PATH: "c:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build"
      TAR: "c:/windows/system32/tar.exe"
      # Avoids port conflicts between concurrent tap test runs
      PG_TEST_USE_UNIX_SOCKETS: 1
      #PG_REGRESS_SOCK_DIR: "c:/temp/"
      MESON_FEATURES: |
        -Dauto_features=disabled
        -Dldap=enabled
        -Dssl=openssl
        -Dtap_tests=enabled
        -Dplperl=enabled
        -Dplpython=enabled
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          repository: postgres/postgres
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_SLONIK }}

      # Restore the cache saved in the sanity-check job
      - name: Populate cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: cache-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: cache-${{ runner.os }}-${{ runner.arch }}-

      - name: Set path
        shell: cmd
        run: echo "${{ env.VCVARS_PATH }}" >> %GITHUB_PATH%

      - name: System information
        shell: cmd
        run: |
          chcp
          systeminfo
          powershell -Command Get-PSDrive -PSProvider filesystem
          set

      - name: Install build dependencies
        shell: cmd
        run: |
          REM choco install -y --no-progress ...

      - name: Configure
        shell: cmd
        run: |
          set
          vcvarsall x64
          meson setup --backend ninja ${{ env.MESON_COMMON_PG_CONFIG_ARGS }} --buildtype debug -Db_pch=true -Dextra_lib_dirs=c:\openssl\1.1\lib -Dextra_include_dirs=c:\openssl\1.1\include -DTAR=${{ env.TAR }} ${{ env.MESON_FEATURES }} build

      - name: Build
        shell: cmd
        run: |
          vcvarsall x64
          ninja -C build ${{ env.MBUILD_TARGET }}
          ninja -C build -t missingdeps

      - name: Test
        shell: cmd
        run: |
          vcvarsall x64
          meson test ${{ env.MTEST_ARGS }} --num-processes ${{ env.TEST_JOBS }}
