name: Linux - Ubuntu - autoconf

on:
  push:
    branches:
      - 'dev/**'

  workflow_dispatch: {}

env:
  BUILD_JOBS: 4
  TEST_JOBS: 8
  CHECK: check-world PROVE_FLAGS=--timer
  CHECKFLAGS: -Otarget

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          repository: postgres/postgres
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_SLONIK }}

      - name: System information
        run: |
          id
          uname -a
          cat /proc/cmdline
          ulimit -a -H && ulimit -a -S
          export

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf bison clang flex gdb gettext \
          libcurl4-openssl-dev libicu-dev libio-pty-perl libipc-run-perl \
          libkrb5-dev libldap2-dev liblz4-dev libnuma-dev libpam0g-dev \
          libperl-dev libreadline-dev libselinux1-dev libssl-dev \
          libsystemd-dev liburing-dev libxml2-dev libxml2-utils libxslt1-dev \
          libzstd-dev llvm-dev lz4 mawk perl pkgconf python3-dev \
          systemtap-sdt-dev tcl-dev tzdata uuid-dev xsltproc zlib1g-dev zstd

      - name: Configure
        run: |
          su postgres <<-EOF
            ./configure \
              --enable-cassert --enable-injection-points --enable-debug \
              --enable-tap-tests --enable-nls \
              --with-segsize-blocks=6 \
              --with-libnuma \
              --with-liburing \
              --with-gssapi \
              --with-icu \
              --with-ldap \
              --with-libcurl \
              --with-libxml \
              --with-libxslt \
              --with-llvm \
              --with-lz4 \
              --with-pam \
              --with-perl \
              --with-python \
              --with-selinux \
              --with-ssl=openssl \
              --with-systemd \
              --with-tcl --with-tclconfig=/usr/lib/tcl8.6/
              --with-uuid=ossp \
              --with-zstd \
              CLANG="ccache clang-16"
          EOF

      - name: Build
        run: |
          su postgres -c "make -s -j${{ env.BUILD_JOBS }} world-bin"

      - name: Run tests
        run: |
          su postgres <<-EOF
            ulimit -c unlimited # default is 0
            make -s ${{ env.CHECK }} ${{ env.CHECKFLAGS }} -j${{ env.TEST_JOBS }}
          EOF
